### ISSUE TITLE
What is Variable N0 stand for in _pooling function

### ISSUE THREAD

**Issue by OrdinaryCrazy** [txie-93/gdynet#1]
```python
def _pooling(inps):
    """
    Pool the atom_fea of target atoms together using their indexes.

    Parameters
    ----------
    atom_fea: (B, N, atom_fea_len)
    target_index: (B, N0)

    Returns
    -------
    crys_fea: (B, N0, atom_fea_len)
    """
    atom_fea, target_index = inps
    B = tf.shape(atom_fea)[0]
    N0 = tf.shape(target_index)[1]
    batch_idx = tf.reshape(tf.range(0, B), (B, 1))
    batch_idx = tf.tile(batch_idx, (1, N0))
    full_idx = tf.stack((batch_idx, target_index), axis=-1)
    return tf.gather_nd(atom_fea, full_idx)
```

**Comment by OrdinaryCrazy** [comment]
I can not figure out how this pooling function works, it just seems like to seperate the target node feature

**Comment by txie-93** [comment]
You are right. This function gathers the target node feature according to the `target_index`. The goal is to get the node embedding of each target atom.

**Comment by OrdinaryCrazy** [comment]
so, i do not understand where do you implement pooling in your code, in which step do you get after pooling embedding of target nodes

**Comment by txie-93** [comment]
I am not sure what you mean exactly. `atom_fea` represents `N` atoms in the system (let's ignore the batch dimension for now). The pooling function takes `N0` target atoms, which are the ones we are interested in, and passes them to the next layer. This is different from the pooling you see in CNNs.

**Comment by OrdinaryCrazy** [comment]
so, your description is however different from the paper, in the paper the pooling is somehow like a normalized mean of the set of nodes, but in your code you just select some ones?? there is no mean as like in cgcnn which refered to use at pooling section.

by the way, for i am a CS engineer, i can not exactly figure out how you decide which node is target node, can you tell me which part of code perform this function

thank you, it is a perfect application of gnn

**Comment by txie-93** [comment]
Okay, I can now see where your confusion comes from. This code is actually for a different paper from CGCNN. In CGCNN, we are interested in predicting property related to the entire graph, so the pooling function has a mean. But in this paper we want to predict property related to target nodes (atoms), so the pooling function just gather those nodes. Check out the paper in the README for more details. And we also have a separate repository of the code for CGCNN.

**Comment by OrdinaryCrazy** [comment]
OK, that's great, certainly I know I am reading code of gdynet, by the way, your cgcnn code is good.

so, my last two question:
1, how do you define the target nodes? in origin data set with fixed index or some metric to judge one node is interesting or not?
2, Is that mean we only interested in whether target nodes' embedding follow the markovain properity rather than the whole set? Does the markovain parameters shared among nodes?

**Comment by OrdinaryCrazy** [comment]
sorry, I think your explaination can not fit the following statement in gdynet paper:
![image](https://user-images.githubusercontent.com/25575097/62314892-f609e780-b448-11e9-9d3b-b430155d0ed7.png)

what do you mean by "set of target nodes"?

this embedding intuitivily not just selection, and it is used for compute loss, it is confusing

**Comment by txie-93** [comment]
You are right. The pooling function here only implements a special case of k=1, so we don’t need to take the mean in this code. Sorry that this is confusing and I will add a note in the code later.

For your questions, 
1. The target nodes are defined in the dataset with fixed indexes. You can find how they are defined in preprocessing section of README.
2. Right. In the scope of this paper, we are interested in Markov models of the nodes (atoms) and the parameters are shared. This is actually one feature that we highlighted in the paper.

**Comment by OrdinaryCrazy** [comment]
Thank you for your help, I will keep following your work, see you soon.
