### ISSUE TITLE
problem during Visualization

### ISSUE THREAD

**Issue by wqchen007** [txie-93/gdynet#5]
dear doc Xie:
I am trying to use gdynet to identify dynamic processes in a friction MD simulation to get specific bonding state for aimed atom. After training the model , I follow the jupyter notebook to visualize the results. When I try to plot the relaxation timescales, something wrong happens just like:

 gdynet/postprocess.py:41: RuntimeWarning: invalid value encountered in log
  its_log_std = np.std(np.log(splited_its), axis=0)
/conda/anaconda3/envs/gdynet/lib/python3.6/site-packages/numpy/core/_methods.py:117: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)

So I check the koopman_op for the array lags, finding there are a lot of zero arrays (the second one): 

[[ 6.7463994e-01 -1.1839467e-01  4.3136746e-01  1.2387081e-02]
 [-5.4880998e-06  9.7734249e-01  2.0228788e-02  2.4341424e-03]
 [ 2.2197758e-04  9.0464517e-02  9.0913689e-01  1.7680590e-04]
 [ 2.5602803e-05  7.5335771e-02 -1.7902499e-02  9.4254106e-01]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

I am wondering which part goes wrong. Thanks a lot!

**Comment by txie-93** [comment]
Thanks for your question! What is your plot of relaxation timescales? Did you see lots of NaNs in that plot? This could happen if you have some very slow dynamics in the system. For example, you have a group of atoms that stays at the same bonding state throughout the entire trajectory. It corresponds to an infinite long relaxation time, which can give NaNs. My experiences is to exclude those as target atoms.

**Comment by wqchen007** [comment]
> Thanks for your question! What is your plot of relaxation timescales? Did you see lots of NaNs in that plot? This could happen if you have some very slow dynamics in the system. For example, you have a group of atoms that stays at the same bonding state throughout the entire trajectory. It corresponds to an infinite long relaxation time, which can give NaNs. My experiences is to exclude those as target atoms.

Thanks for your answering! Just as yous say, there are lots of NaNs in the plot of relaxation timescales. And when I aimed at the atoms in the interface layer which have clear states change, the problem are solved! Thanks a lot!
